phraseapp:
  access_token: "063c6e66ff5dc3f349e23a337a6795b2fd8aca8344ae877b92f9d7150e629a1d"
  project_id: "2bc068cf9ed5989e19eefbc0c591be45"
  file_format: "csv"
  push:
    sources:
    - file: "./en.csv"
      params:
        locale_id: "5f529760b8cad6de1d370e9adbc519f9"
        update_translations: true
        update_descriptions: true
        format_options:
          key_index: 1
          translation_index: 2
          comment_index: 3
  pull:
    targets:
    - file: "./en.csv"
      params:
        locale_id: "5f529760b8cad6de1d370e9adbc519f9"